### ISSUE TITLE
IndexError on Raspberry Pi 

### ISSUE THREAD

**Issue by pbricmont** [adafruit/Adafruit_CircuitPython_DymoScale#5]
Trying to use DymoScale with the Raspberry Pi 3B+ running the lastest Raspbian Buster and getting this:

File "/home/pi/dymoscale_simple.py", line 15, in <module>
    reading = dymo.weight
  File "/usr/local/lib/python3.7/dist-packages/adafruit_dymoscale.py", line 76, in weight
    reading = self.get_scale_data()
  File "/usr/local/lib/python3.7/dist-packages/adafruit_dymoscale.py", line 122, in get_scale_data
    bits[bit_idx] = bit_val
IndexError: list assignment index out of range

I'm using the lastest versions of Blinka, Dymoscale, and libgpiod. I've confirmed that the scale is wired correctly using a Metro M4 Express. Any ideas?

Thanks

**Comment by ladyada** [comment]
might not be able to use a pi because of the very sensitive timing....the protocol hacking is pretty delicate!

**Comment by pbricmont** [comment]
I was afraid that was going to be the answer but thanks for the reply all the same. I will investigate other options. Thanks

**Comment by ladyada** [comment]
@brentru plz add a note to this repo' that it wont work on embedded linux - only microcontrollers :)
